#!/usr/bin/env bash
# Opt-in smoke for deploy/local: admin BFF + **real SPA** baked into the image.
#
# NOT part of default `make test` / `make ci`. Requires Docker Compose v2.
#
# Checks:
#   - stack builds and comes up (admin on 127.0.0.1:8787)
#   - GET /admin/v1/health returns 200 with non-placeholder uiBuild
#   - GET / is 200 HTML SPA shell (id="root" / /assets/ script — not placeholder)
#   - GET /metrics SPA deep-link returns index shell (UI-008 fallback)
#   - secret canary does not appear in SPA or health JSON
#
# Usage (repo root):
#   make local-docker-smoke
#   scripts/local-docker-smoke.sh
#   SKIP_DOWN=1 scripts/local-docker-smoke.sh   # leave stack running
#   SKIP_UP=1 scripts/local-docker-smoke.sh     # assume already up
#
# Exit: 0 on pass; non-zero on failure.
set -euo pipefail

export PATH="${HOME}/.local/go/bin:/usr/local/go/bin:${HOME}/.local/node-v22.14.0-linux-x64/bin:${PATH:-}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if ! command -v docker >/dev/null 2>&1; then
  echo "FAIL: docker required" >&2
  exit 1
fi

COMPOSE_FILE="${LOCAL_COMPOSE_FILE:-$ROOT/deploy/local/docker-compose.yml}"
ENV_FILE="${LOCAL_ENV_FILE:-$ROOT/deploy/local/.env}"
HOST_PORT="${LOCAL_ADMIN_HOST_PORT:-8787}"
BASE_URL="http://127.0.0.1:${HOST_PORT}"
HELPER="${ROOT}/scripts/local-docker.sh"
SKIP_UP="${SKIP_UP:-0}"
SKIP_DOWN="${SKIP_DOWN:-0}"
# Wait budget for health (image build can be long; start_period already handles cold start).
WAIT_SECS="${WAIT_SECS:-180}"

chmod +x "$HELPER" 2>/dev/null || true

# Ensure .env exists with a disposable lab token (never commit real secrets).
if [[ ! -f "$ENV_FILE" ]]; then
  cp "$ROOT/deploy/local/.env.example" "$ENV_FILE"
  echo "created $ENV_FILE from example"
fi
# shellcheck disable=SC1090
set -a
# shellcheck source=/dev/null
source "$ENV_FILE" 2>/dev/null || true
set +a

if [[ -z "${JENKINS_MCP_ADMIN_TOKEN:-}" ]]; then
  # Plant a lab token so non-loopback admin serve path is exercised with require-token.
  LAB_TOKEN="local-docker-smoke-$(openssl rand -hex 12 2>/dev/null || date +%s)"
  {
    echo ""
    echo "# generated by scripts/local-docker-smoke.sh (lab only)"
    echo "JENKINS_MCP_ADMIN_TOKEN=${LAB_TOKEN}"
  } >>"$ENV_FILE"
  export JENKINS_MCP_ADMIN_TOKEN="$LAB_TOKEN"
  echo "planted lab JENKINS_MCP_ADMIN_TOKEN in $ENV_FILE"
else
  export JENKINS_MCP_ADMIN_TOKEN
fi

# Canary: token must never appear in SPA HTML or health JSON bodies.
CANARY="${JENKINS_MCP_ADMIN_TOKEN}"

VERSION="${VERSION:-$(git describe --tags --always --dirty 2>/dev/null || echo dev)}"
COMMIT="${COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || echo unknown)}"
BUILDTIME="${BUILDTIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
export VERSION COMMIT BUILDTIME
export LOCAL_ADMIN_HOST_PORT="$HOST_PORT"

cleanup() {
  local ec=$?
  if [[ "$SKIP_DOWN" != "1" && "$SKIP_DOWN" != "true" ]]; then
    echo "== tear down (SKIP_DOWN=0) =="
    "$HELPER" down || true
  else
    echo "== leave stack up (SKIP_DOWN=${SKIP_DOWN}) =="
  fi
  exit "${ec}"
}
trap cleanup EXIT INT TERM

if [[ "$SKIP_UP" != "1" && "$SKIP_UP" != "true" ]]; then
  echo "== build + up (VERSION=${VERSION} COMMIT=${COMMIT}) =="
  VERSION="$VERSION" COMMIT="$COMMIT" BUILDTIME="$BUILDTIME" "$HELPER" up
else
  echo "== SKIP_UP: using existing stack at ${BASE_URL} =="
fi

auth_hdr=(-H "Authorization: Bearer ${JENKINS_MCP_ADMIN_TOKEN}")

echo "== wait for health (${WAIT_SECS}s) =="
deadline=$((SECONDS + WAIT_SECS))
health_body=""
while (( SECONDS < deadline )); do
  if health_body="$(curl -fsS "${auth_hdr[@]}" "${BASE_URL}/admin/v1/health" 2>/dev/null)"; then
    break
  fi
  sleep 2
done
if [[ -z "$health_body" ]]; then
  echo "FAIL: health not ready at ${BASE_URL}/admin/v1/health within ${WAIT_SECS}s" >&2
  "$HELPER" ps || true
  "$HELPER" logs 2>/dev/null | tail -n 80 || true
  exit 1
fi
echo "health: $health_body"

# uiBuild must be present and not the embed placeholder.
if ! printf '%s' "$health_body" | grep -q '"uiBuild"'; then
  echo "FAIL: health JSON missing uiBuild" >&2
  exit 1
fi
if printf '%s' "$health_body" | grep -Eqi '"uiBuild"[[:space:]]*:[[:space:]]*"(embedded-placeholder|placeholder|)"'; then
  echo "FAIL: uiBuild is empty or placeholder — SPA not packaged in image" >&2
  exit 1
fi
if printf '%s' "$health_body" | grep -Fq "$CANARY"; then
  echo "FAIL: admin token canary leaked into health JSON" >&2
  exit 1
fi
ui_build="$(printf '%s' "$health_body" | sed -n 's/.*"uiBuild"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
echo "ok: health uiBuild=${ui_build}"

echo "== GET / (SPA shell) =="
# Static SPA is not gated by admin token (loopback residual).
spa_code="$(curl -sS -o /tmp/local-docker-spa-index.html -w '%{http_code}' "${BASE_URL}/")"
spa_body="$(cat /tmp/local-docker-spa-index.html)"
if [[ "$spa_code" != "200" ]]; then
  echo "FAIL: GET / expected 200, got ${spa_code}" >&2
  exit 1
fi
# Must be real SPA, not embed/placeholder HTML.
if printf '%s' "$spa_body" | grep -Eqi 'SPA assets are not bundled|Full SPA assets were not baked|No SPA assets resolved|Embedded placeholder UI'; then
  echo "FAIL: GET / returned placeholder HTML, not packaged SPA" >&2
  printf '%s\n' "$spa_body" | head -n 40 >&2
  exit 1
fi
# Vite production shell markers (title + root mount and/or hashed assets).
if ! printf '%s' "$spa_body" | grep -Eqi 'id=["'\'']root["'\'']|/assets/|jenkins-mcp'; then
  echo "FAIL: GET / missing SPA shell markers (root/assets/jenkins-mcp)" >&2
  printf '%s\n' "$spa_body" | head -n 40 >&2
  exit 1
fi
if printf '%s' "$spa_body" | grep -Fq "$CANARY"; then
  echo "FAIL: admin token canary leaked into SPA HTML" >&2
  exit 1
fi
echo "ok: GET / SPA shell (${#spa_body} bytes)"

echo "== GET /metrics (BrowserRouter deep-link → index shell) =="
deep_code="$(curl -sS -o /tmp/local-docker-spa-metrics.html -w '%{http_code}' "${BASE_URL}/metrics")"
deep_body="$(cat /tmp/local-docker-spa-metrics.html)"
if [[ "$deep_code" != "200" ]]; then
  echo "FAIL: GET /metrics expected 200 SPA shell, got ${deep_code}" >&2
  exit 1
fi
if printf '%s' "$deep_body" | grep -Eqi 'SPA assets are not bundled|Full SPA assets were not baked|No SPA assets resolved|Embedded placeholder UI'; then
  echo "FAIL: GET /metrics returned placeholder HTML" >&2
  exit 1
fi
if ! printf '%s' "$deep_body" | grep -Eqi 'id=["'\'']root["'\'']|/assets/|jenkins-mcp'; then
  echo "FAIL: GET /metrics missing SPA shell markers" >&2
  exit 1
fi
echo "ok: GET /metrics SPA fallback shell"

# Optional: hashed asset path from index should 200 if present.
asset_path="$(printf '%s' "$spa_body" | grep -oE '/assets/[^"'\'' ]+\.js' | head -1 || true)"
if [[ -n "$asset_path" ]]; then
  echo "== GET ${asset_path} =="
  asset_code="$(curl -sS -o /dev/null -w '%{http_code}' "${BASE_URL}${asset_path}")"
  if [[ "$asset_code" != "200" ]]; then
    echo "FAIL: SPA asset ${asset_path} expected 200, got ${asset_code}" >&2
    exit 1
  fi
  echo "ok: SPA asset ${asset_path}"
fi

echo ""
echo "PASS: local Docker admin SPA smoke (uiBuild=${ui_build})"
echo "  Admin: ${BASE_URL}"
echo "  Tear down: make local-docker-down  (or this script unless SKIP_DOWN=1)"
